//
// Created by Trung Ngo on 19/12/2022.
//

#ifndef SSET_APT_HOUSE_VACATION_PROJECT_ADMIN_H
#define SSET_APT_HOUSE_VACATION_PROJECT_ADMIN_H


class Admin {

};


#endif //SSET_APT_HOUSE_VACATION_PROJECT_ADMIN_H
